// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zHjMxbovLMhp-1WxNFbzJO3G-6AEXps',
    appId: '1:410572987272:web:bb6710968891bc9e83783d',
    messagingSenderId: '410572987272',
    projectId: 'saloon-shop-official',
    authDomain: 'saloon-shop-official.firebaseapp.com',
    storageBucket: 'saloon-shop-official.firebasestorage.app',
    measurementId: 'G-JY1J7SM2B9',
    databaseURL: 'https://saloon-shop-official-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_ZHGkorEeM7cqBJWMdbyvKBUm5S_Ajo',
    appId: '1:410572987272:android:183d56833a593a2283783d',
    messagingSenderId: '410572987272',
    projectId: 'saloon-shop-official',
    storageBucket: 'saloon-shop-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0145sMPn6F55FYjbdQa29Qr_wD9vSDfE',
    appId: '1:410572987272:ios:80eb8ab590491bc483783d',
    messagingSenderId: '410572987272',
    projectId: 'saloon-shop-official',
    storageBucket: 'saloon-shop-official.firebasestorage.app',
    iosBundleId: 'com.example.saloon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0145sMPn6F55FYjbdQa29Qr_wD9vSDfE',
    appId: '1:410572987272:ios:80eb8ab590491bc483783d',
    messagingSenderId: '410572987272',
    projectId: 'saloon-shop-official',
    storageBucket: 'saloon-shop-official.firebasestorage.app',
    iosBundleId: 'com.example.saloon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zHjMxbovLMhp-1WxNFbzJO3G-6AEXps',
    appId: '1:410572987272:web:ccad5a52cae0ce8f83783d',
    messagingSenderId: '410572987272',
    projectId: 'saloon-shop-official',
    authDomain: 'saloon-shop-official.firebaseapp.com',
    storageBucket: 'saloon-shop-official.firebasestorage.app',
    measurementId: 'G-MXV5BM758J',
  );
}
