// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfPlRV0mQr5xUW27VjkqUD5qhyowkwaHI',
    appId: '1:22799517517:web:59a0e9f5f89c21c16a5904',
    messagingSenderId: '22799517517',
    projectId: 'modern-cut-org',
    authDomain: 'modern-cut-org.firebaseapp.com',
    databaseURL: 'https://modern-cut-org-default-rtdb.firebaseio.com',
    storageBucket: 'modern-cut-org.firebasestorage.app',
    measurementId: 'G-LQ35DPYJYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGyO8_qmS5i5nPH537R9HHYNvI7zwS9U',
    appId: '1:22799517517:android:9214b4e3bfe9f17f6a5904',
    messagingSenderId: '22799517517',
    projectId: 'modern-cut-org',
    databaseURL: 'https://modern-cut-org-default-rtdb.firebaseio.com',
    storageBucket: 'modern-cut-org.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_NiY2ThRn73tO4Wim3ToSjHjWmW8XLA',
    appId: '1:22799517517:ios:2fc414fd74638f726a5904',
    messagingSenderId: '22799517517',
    projectId: 'modern-cut-org',
    databaseURL: 'https://modern-cut-org-default-rtdb.firebaseio.com',
    storageBucket: 'modern-cut-org.firebasestorage.app',
    iosBundleId: 'com.example.saloon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_NiY2ThRn73tO4Wim3ToSjHjWmW8XLA',
    appId: '1:22799517517:ios:2fc414fd74638f726a5904',
    messagingSenderId: '22799517517',
    projectId: 'modern-cut-org',
    databaseURL: 'https://modern-cut-org-default-rtdb.firebaseio.com',
    storageBucket: 'modern-cut-org.firebasestorage.app',
    iosBundleId: 'com.example.saloon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfPlRV0mQr5xUW27VjkqUD5qhyowkwaHI',
    appId: '1:22799517517:web:9c9b556664119a106a5904',
    messagingSenderId: '22799517517',
    projectId: 'modern-cut-org',
    authDomain: 'modern-cut-org.firebaseapp.com',
    databaseURL: 'https://modern-cut-org-default-rtdb.firebaseio.com',
    storageBucket: 'modern-cut-org.firebasestorage.app',
    measurementId: 'G-JD3SMZD8T8',
  );

}